version: 2
updates:
  # Enable version updates for uv
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
